import type { Metadata } from "next";

import "./globals.css";
import AOSInitializer from "@/components/AOSInitializer";

export const metadata: Metadata = {
  title: "Yazzi App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-neutral-950 text-white">
        <AOSInitializer />
        {children}
      </body>
    </html>
  );
}
